name: Run Databricks Bundle Job

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-job:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Deploy bundle to dev
        run: databricks bundle deploy -t dev

      - name: Run bundle job
        run: databricks bundle run sample_job -t dev
